CREATE TABLE captain (
  email  varchar(50) PRIMARY KEY,
  name   varchar(50) NOT NULL,
  color  varchar(20)
);

CREATE TABLE special_date (
  day    date PRIMARY KEY,
  type   varchar(20) NOT NULL,
  label  varchar(50)
);

CREATE TABLE trip (
  id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  day   varchar(10) NOT NULL,
  data  json NOT NULL
);
CREATE INDEX trip_day_idx ON trip (day);

